project_name: tools

env:
  - CGO_ENABLED=0
  - GO111MODULE=ons

builds:
- id: "getAllVilla_linux"
  main: ./tools/getAllVilla
  goos:
    - linux
  goarch:
    - 386
    - amd64
    - arm
    - arm64
  goarm:
    - 6
    - 7
  mod_timestamp: "{{ .CommitTimestamp }}"
  flags:
    - -trimpath
  ldflags:
    - -s -w
- id: "getAllVilla_win"
  main: ./tools/getAllVilla
  goos:
    - windows
  goarch:
    - 386
    - amd64
  mod_timestamp: "{{ .CommitTimestamp }}"
  flags:
    - -trimpath
  ldflags:
    - -s -w
- id: "getAllVilla_mac"
  main: ./tools/getAllVilla
  goos:
    - darwin
  goarch:
    - amd64
  mod_timestamp: "{{ .CommitTimestamp }}"
  flags:
    - -trimpath
  ldflags:
    - -s -w

  # - main: ./cmd/worker
  #   id: "worker"
  #   binary: worker
  #   goos:
  #     - linux
  #     - darwin
  #     - windows

  # - main: ./cmd/tracker
  #   id: "tracker"
  #   binary: tracker
  #   goos:
  #     - linux
  #     - darwin
  #     - windows
