project_name: tools

env:
  - CGO_ENABLED=0
  - GO111MODULE=on

builds:
- id: "getAllVilla"
  main: ./tools/getAllVilla/main.go
  binary: getAllVilla
  goos:
    - darwin
    - windows
    - linux
  goarch:
    - 386
    - amd64
    - arm
    - arm64
  goarm:
    - 6
    - 7
  ignore:
    - goos: darwin
      goarch: 386
  mod_timestamp: "{{ .CommitTimestamp }}"
  flags:
    - -trimpath
  ldflags:
    - -s -w

archives:
- id: "getAllVilla"
  builds:
    - "getAllVilla"
  replacements:
    darwin: macos
    386: i386
    amd64: x86_64
  name_template: "getAllVilla_v{{ .Tag }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
  format_overrides:
    - goos: windows
      format: zip
  wrap_in_directory: true
  files:
    - ./tools/getAllVilla/config.yaml
