project_name: tools

env:
  - CGO_ENABLED=0
  - GO111MODULE=on

builds:
- id: "getAllVilla_linux"
  main: ./tools/getAllVilla/main.go
  binary: getAllVilla
  goos:
    - linux
  goarch:
    - 386
    - amd64
    - arm
    - arm64
  goarm:
    - 6
    - 7
  mod_timestamp: "{{ .CommitTimestamp }}"
  flags:
    - -trimpath
  ldflags:
    - -s -w
- id: "getAllVilla_win"
  main: ./tools/getAllVilla/main.go
  binary: getAllVilla.exe
  goos:
    - windows
  goarch:
    - 386
    - amd64
  mod_timestamp: "{{ .CommitTimestamp }}"
  flags:
    - -trimpath
  ldflags:
    - -s -w
- id: "getAllVilla_mac"
  main: ./tools/getAllVilla/main.go
  binary: getAllVilla
  goos:
    - darwin
  goarch:
    - amd64
  mod_timestamp: "{{ .CommitTimestamp }}"
  flags:
    - -trimpath
  ldflags:
    - -s -w

archives:
- id: "getAllVilla"
  builds:
      - "getAllVilla_linux"
      - "getAllVilla_win"
      - "getAllVilla_mac"
  name_template: "getAllVilla_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
  format_overrides:
      - goos: windows
        format: zip
