# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
    
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.53
        args: -D errcheck -E asciicheck -E bodyclose -E goconst -E godox -E gomodguard -E whitespace -E unconvert -E unparam -E usestdlibvars -E tagalign 
