name: release

on:
    push:
        tags:
          - '*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@master
        with:
          go-version: '1.20'

      - name: Go mod tidy
        uses: evantorrie/mott-the-tidier@v1-beta
        with:
          gomods: |
            **/go.mod
            -tools/getAllVilla/go.mod

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@master
        with:
          distribution: goreleaser
          version: latest
          args: release -f .goreleaser.yml --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}